app/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

# estas urls llaman a funciones para actualizar el carrito
urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Estas Urls son especiales, pues en realidad están “heredando” las
# distintas urls que contienen los otros módulos


urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include("autenticacion.urls")),
    path('product/', include("products.urls")),
    path('', include("products.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/products/urls.py
from django.urls import path
from .views import listado_productos,carrito_cel

urlpatterns = [
    path('', listado_productos, name='listado_productos'),
    path('carrito_cel/', carrito_cel, name='carrito_cel')
]

app/cart/models.py
from django.db import models

# Create your models here.

app/products/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=300)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ['-id']


# Product Model
class Product(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', blank=True)
    excerpt = models.TextField(max_length=200, verbose_name='Extracto')
    detail = models.TextField(max_length=1000, verbose_name='Información del producto')
    price = models.FloatField()
    tallaG = models.IntegerField(default=1)
    tallaM = models.IntegerField(default=1)
    tallaC = models.IntegerField(default=1)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'products'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']

app/cart/views.py
from django.shortcuts import render, redirect
from products.models import Product
from django.contrib.auth.decorators import login_required
from .cart import Cart


# login_required sirve para obligar al usuario a entrar a su sesión
@login_required(login_url='/autenticacion/acceder')
def add_product(request, product_id): # agrega productos
    cart = Cart(request)    # actualiza
    product = Product.objects.get(id=product_id)
    cart.add(product=product)
    return redirect("listado_productos")


@login_required(login_url='/autenticacion/acceder')
def remove_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.remove(product)
    return redirect("listado_productos")


@login_required(login_url='/autenticacion/acceder')
def decrement_product(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.decrement(product=product)
    return redirect("listado_productos")


@login_required(login_url='/autenticacion/acceder')
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("listado_productos")

app/products/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from products.models import Product
from cart.cart import Cart
from django.core.paginator import Paginator
# Create your views here.


def listado_productos(request):
    cart = Cart(request)
    listado_product = Product.objects.all()
    paginator = Paginator(listado_product, 6)
    pagina = request.GET.get("page") or 1
    products = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, products.paginator.num_pages + 1)
    return render(request, "products/listado.html", {
        "products": products, "paginas": paginas, "pagina_actual": pagina_actual
    })


def carrito_cel(request):
    cart = Cart(request)
    listado_product = Product.objects.all()
    paginator = Paginator(listado_product, 6)
    pagina = request.GET.get("page") or 1
    products = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, products.paginator.num_pages + 1)
    return render(request, "cart/cel_cart.html", {
        "products": products, "paginas": paginas, "pagina_actual": pagina_actual
    })

app/products/templates/cart/cel_cart.html
{% extends 'layout/tienda.html' %}

{% load cart_tags %}
{% block title %} Greaser - Inicio {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            {% include "cart/widget.html" %}
        </div>
    </div>
{% endblock %}

app/products/templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
    <thead style="background-color: rgba(53, 54, 58, 70%); color: white;">
    <tr>
        <th colspan="3" class="text-center" style="background-color: rgba(53, 54, 58, 70%); color: white;">
            Compras
        </th>
    </tr>
    <tr>
        <th>Product</th>
        <th>Cantidad</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody style="background-color: rgba(53, 54, 58, 70%); color: white;">
    {% if request.session.cart.items %}
        {% for key, value in request.session.cart.items %}
            <tr class="text-center">
                <td>{{ value.name }}</td>
                <td>{{ value.quantity }}</td>
                <td>
                    <a href="{% url 'cart:add_product' value.product_id %}"
                       class="btn btn-sm btn-success"
                    >
                        +
                    </a>
                    <a href="{% url 'cart:decrement_product' value.product_id %}"
                       class="ml-2 btn-sm btn btn-danger"
                    >
                        -
                    </a>
                    Total: {{ value.price|multiply:value.quantity|money_format:"$" }}
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">
                <div class="alert alert-danger text-center">
                    No tienes productos en el carrito
                </div>
            </td>
        </tr>
    {% endif %}
    </tbody>
    <tfoot style="background-color: rgba(53, 54, 58, 70%); color: white;">
    <tr>
        <td colspan="3">
            Total: {{ cart_total_amount|money_format:"$" }} MXN
        </td>
    </tr>
    {% if request.session.cart.items %}
        <tr>
            <td colspan="3" class="text-center">
                <a href="{% url 'process_order' %}" class="btn btn-success"> crear pedido</a>
            </td>
        </tr>
    {% endif %} 
    </tfoot>
</table>